version: '3.4'

services:
  hassancehef-bookingreferenceservice:
    image: ${DOCKER_REGISTRY-}hassancehefbookingreferenceservice
    build:
      context: .
      dockerfile: HassanCehef/HassanCehef.BookingReferenceService/Dockerfile

  hassancehef-traindataservice:
    image: ${DOCKER_REGISTRY-}hassanceheftraindataservice
    build:
      context: .
      dockerfile: HassanCehef/HassanCehef.TrainDataService/Dockerfile

  traintrain-api:
    image: ${DOCKER_REGISTRY-}traintrainapi
    build:
      context: .
      dockerfile: TrainTrain.Api/Dockerfile

