version: '3.4'

services:
  railway.bookingreferenceservice:
    image: ${DOCKER_REGISTRY-}railwaybookingreferenceservice
    build:
      context: .
      dockerfile: Railway/Railway.BookingReferenceService/Dockerfile

  railway.traindataservice:
    image: ${DOCKER_REGISTRY-}railwaytraindataservice
    build:
      context: .
      dockerfile: Railway/Railway.TrainDataService/Dockerfile

  traintrain.api:
    image: ${DOCKER_REGISTRY-}traintrainapi
    build:
      context: .
      dockerfile: TrainTrain.Api/Dockerfile

